version: "3.8"
services:
  database: 
    image: mysql
    restart: always
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=mysql
      #- MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
    volumes:
      - ~/db/data:/usr/local/var/mysql:rw
      - ~/db/conf:/usr/local/etc:rw
  webapp:
    image: webapp-project
    build:
      context: ./build/libs
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mysql?useSSL=false&allowPublicKeyRetrieval=true&serverTimeZone=UTC&CharacterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - database